VERSION: 2
DATALOADER:
  NUM_WORKERS: 1
INPUT:
  MASK_FORMAT: "bitmask"  # alternative: "polygon"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530] # This RGB, for BGR order: [103.530, 116.280, 123.675]
  PIXEL_STD: [58.395, 57.120, 57.375] # This RGB, for BGR order: [57.375, 57.120, 58.395]
  MASK_ON: True
  BACKBONE:
    NAME: "build_dino_resnet_fpn_backbone"
#    NAME: "build_resnet_fpn_backbone"

#  ROI_HEADS:
#    NUM_CLASSES: 2
#  META_ARCHITECTURE: "ResNetDINO" # TODO
DATASETS:
#  TRAIN: ("coco_20k_class_agnostic",)
#  TEST: ("coco_20k_class_agnostic",)
    TRAIN: ("coco_2017_val",)
    TEST: ("coco_2017_val",)
SOLVER:
#  STEPS: (210000, 250000)
  STEPS: (220000,)
  CHECKPOINT_PERIOD: 5000
  MAX_ITER: 240000
  IMS_PER_BATCH: 1
  BASE_LR: 0.02
OUTPUT_DIR: "checkpoints/train_base"
